#pragma once

#include <string>
#include <vector>
#include <cstdint>

enum mfq_text_chat_template {
    MFQ_TEXT_CHAT_TEMPLATE_CHATML,
    MFQ_TEXT_CHAT_TEMPLATE_META_2,
    MFQ_TEXT_CHAT_TEMPLATE_META_2_SYS,
    MFQ_TEXT_CHAT_TEMPLATE_META_2_SYS_BOS,
    MFQ_TEXT_CHAT_TEMPLATE_META_2_SYS_STRIP,
    MFQ_TEXT_CHAT_TEMPLATE_MISTRAL_V1,
    MFQ_TEXT_CHAT_TEMPLATE_MISTRAL_V3,
    MFQ_TEXT_CHAT_TEMPLATE_MISTRAL_V3_TEKKEN,
    MFQ_TEXT_CHAT_TEMPLATE_MISTRAL_V7,
    MFQ_TEXT_CHAT_TEMPLATE_MISTRAL_V7_TEKKEN,
    MFQ_TEXT_CHAT_TEMPLATE_PHI_3,
    MFQ_TEXT_CHAT_TEMPLATE_PHI_4,
    MFQ_TEXT_CHAT_TEMPLATE_FALCON_3,
    MFQ_TEXT_CHAT_TEMPLATE_ZEPHYR,
    MFQ_TEXT_CHAT_TEMPLATE_MONARCH,
    MFQ_TEXT_CHAT_TEMPLATE_GEMMA,
    MFQ_TEXT_CHAT_TEMPLATE_ORION,
    MFQ_TEXT_CHAT_TEMPLATE_OPENCHAT,
    MFQ_TEXT_CHAT_TEMPLATE_VICUNA,
    MFQ_TEXT_CHAT_TEMPLATE_VICUNA_ORCA,
    MFQ_TEXT_CHAT_TEMPLATE_DEEPSEEK,
    MFQ_TEXT_CHAT_TEMPLATE_DEEPSEEK_2,
    MFQ_TEXT_CHAT_TEMPLATE_DEEPSEEK_3,
    MFQ_TEXT_CHAT_TEMPLATE_DEEPSEEK_OCR,
    MFQ_TEXT_CHAT_TEMPLATE_COMMAND_R,
    MFQ_TEXT_CHAT_TEMPLATE_META_3,
    MFQ_TEXT_CHAT_TEMPLATE_CHATGLM_3,
    MFQ_TEXT_CHAT_TEMPLATE_CHATGLM_4,
    MFQ_TEXT_CHAT_TEMPLATE_GLMEDGE,
    MFQ_TEXT_CHAT_TEMPLATE_MINICPM,
    MFQ_TEXT_CHAT_TEMPLATE_EXAONE_3,
    MFQ_TEXT_CHAT_TEMPLATE_EXAONE_4,
    MFQ_TEXT_CHAT_TEMPLATE_EXAONE_MOE,
    MFQ_TEXT_CHAT_TEMPLATE_RWKV_WORLD,
    MFQ_TEXT_CHAT_TEMPLATE_GRANITE_3_X,
    MFQ_TEXT_CHAT_TEMPLATE_GRANITE_4_0,
    MFQ_TEXT_CHAT_TEMPLATE_GRANITE_4_1,
    MFQ_TEXT_CHAT_TEMPLATE_GIGACHAT,
    MFQ_TEXT_CHAT_TEMPLATE_MEGREZ,
    MFQ_TEXT_CHAT_TEMPLATE_YANDEX,
    MFQ_TEXT_CHAT_TEMPLATE_BAILING,
    MFQ_TEXT_CHAT_TEMPLATE_BAILING_THINK,
    MFQ_TEXT_CHAT_TEMPLATE_BAILING2,
    MFQ_TEXT_CHAT_TEMPLATE_META_4,
    MFQ_TEXT_CHAT_TEMPLATE_SMOLVLM,
    MFQ_TEXT_CHAT_TEMPLATE_DOTS1,
    MFQ_TEXT_CHAT_TEMPLATE_HUNYUAN_MOE,
    MFQ_TEXT_CHAT_TEMPLATE_OPENAI_MOE,
    MFQ_TEXT_CHAT_TEMPLATE_HUNYUAN_DENSE,
    MFQ_TEXT_CHAT_TEMPLATE_HUNYUAN_VL,
    MFQ_TEXT_CHAT_TEMPLATE_KIMI_K2,
    MFQ_TEXT_CHAT_TEMPLATE_SEED_OSS,
    MFQ_TEXT_CHAT_TEMPLATE_GROK_2,
    MFQ_TEXT_CHAT_TEMPLATE_PANGU_EMBED,
    MFQ_TEXT_CHAT_TEMPLATE_SOLAR_OPEN,
    MFQ_TEXT_CHAT_TEMPLATE_UNKNOWN,
};

struct mfq_text_chat_message;

mfq_text_chat_template mfq_text_chat_template_from_str(const std::string & name);

mfq_text_chat_template mfq_text_chat_detect_template(const std::string & tmpl);

int32_t mfq_text_chat_apply_template(
    mfq_text_chat_template tmpl,
    const std::vector<const mfq_text_chat_message *> & chat,
    std::string & dest, bool add_ass);
