"""Non-training calibration artifacts and discrete allocation APIs."""

from mfq.calibration.allocator import AllocationResult, GroupCandidate, allocate
from mfq.calibration.artifact import (
    CalibrationScheme,
    ExpertPrecision,
    ExpertSelection,
    ExpertTensorSelection,
    TensorSelection,
    load_scheme,
    nint_expert_precision,
    save_scheme,
    scheme_expert_precisions,
    scheme_expert_specs,
)
from mfq.calibration.ew_solver import (
    EwBudget,
    EwCandidate,
    EwCandidateTable,
    EwItemKey,
    EwSolveResult,
    EwTensorSpec,
    HistogramConstraint,
    ImportanceEntry,
    ImportanceTable,
    RateBounds,
    ShapeConstraint,
    load_budget,
    load_budget_document,
    load_candidate_document,
    load_candidate_table,
    load_importance_document,
    load_importance_table,
    solve_ew_budget,
)

__all__ = [
    "AllocationResult",
    "CalibrationScheme",
    "ExpertPrecision",
    "ExpertSelection",
    "ExpertTensorSelection",
    "EwBudget",
    "EwCandidate",
    "EwCandidateTable",
    "EwItemKey",
    "EwSolveResult",
    "EwTensorSpec",
    "GroupCandidate",
    "HistogramConstraint",
    "ImportanceEntry",
    "ImportanceTable",
    "RateBounds",
    "ShapeConstraint",
    "TensorSelection",
    "allocate",
    "load_budget",
    "load_budget_document",
    "load_candidate_document",
    "load_candidate_table",
    "load_importance_document",
    "load_importance_table",
    "load_scheme",
    "nint_expert_precision",
    "save_scheme",
    "scheme_expert_precisions",
    "scheme_expert_specs",
    "solve_ew_budget",
]
