"""TPQ 通用算子层。"""

from .api import (
    attention_step,
    block_scaled_gemm,
    block_scaled_gemv,
    block_scaled_grouped_gemm,
    block_scaled_grouped_gemv,
    block_scaled_grouped_rows_gemv,
    compressed_state_update,
    create_resident_projection_layer,
    create_resident_moe_layer,
    create_latent_resident_moe_layer,
    dense_grouped_gemv,
    dense_gemv,
    head_rmsnorm_rope,
    create_tensor_parallel,
    gated_activation,
    hyper_connection_post,
    hyper_connection_post_moe,
    hyper_connection_pre_norm,
    linear,
    linear_grouped_rows,
    linear_route_topk,
    packed_moe_topk,
    packed_moe_selected_topk,
    packed_moe_operator_name,
    packed_route_slots,
    resident_moe_topk,
    residual_add3,
    residual_mix,
    route_topk,
    rmsnorm,
    vq_gemv,
    vq_gemv_packed_list,
    vq_relayout_block_major,
    vq_relayout_row_tile,
    vq_compile_u16_row_tile,
)
from .hidden import TPHidden, TPPartials, TPResidualBuffer, TPSharded
from .moe import FixedMoEPrelude, FixedMoEPreludeSpec
from .profiling import TPHiddenStageProfiler
from .config import ModelOperatorConfig
from .registry import OperatorRegistry, REGISTRY
from .spec import OperatorCapability, OperatorRequest
from .fixed_graph import FixedAddressCudaGraph
from .tensor_parallel import (
    PackedMoEFinalizerSpec,
    ReplicatedLinearSpec,
    ReplicatedSubgroupTensorParallel,
    RoutePackedPlanSpec,
    TensorParallelAllRankCollective,
    TensorParallelDecodeLayerPlan,
    TensorParallelMoELayerPlan,
    TensorParallelPackedMoEFinalizer,
    TensorParallelReplicatedLinear,
    TensorParallelRoutePackedPlan,
    TensorParallelVocab,
    shard_linear_input,
    shard_linear_output,
)

__all__ = [
    "ModelOperatorConfig",
    "OperatorCapability",
    "OperatorRegistry",
    "OperatorRequest",
    "FixedAddressCudaGraph",
    "REGISTRY",
    "attention_step",
    "block_scaled_gemm",
    "block_scaled_gemv",
    "block_scaled_grouped_gemm",
    "block_scaled_grouped_gemv",
    "block_scaled_grouped_rows_gemv",
    "compressed_state_update",
    "create_resident_projection_layer",
    "create_resident_moe_layer",
    "create_latent_resident_moe_layer",
    "dense_grouped_gemv",
    "dense_gemv",
    "head_rmsnorm_rope",
    "create_tensor_parallel",
    "gated_activation",
    "hyper_connection_post",
    "hyper_connection_post_moe",
    "hyper_connection_pre_norm",
    "linear",
    "linear_grouped_rows",
    "linear_route_topk",
    "packed_moe_topk",
    "packed_moe_selected_topk",
    "packed_moe_operator_name",
    "packed_route_slots",
    "resident_moe_topk",
    "residual_add3",
    "residual_mix",
    "route_topk",
    "rmsnorm",
    "TPHidden",
    "TPHiddenStageProfiler",
    "TPPartials",
    "TPResidualBuffer",
    "TPSharded",
    "PackedMoEFinalizerSpec",
    "ReplicatedLinearSpec",
    "ReplicatedSubgroupTensorParallel",
    "RoutePackedPlanSpec",
    "TensorParallelAllRankCollective",
    "TensorParallelMoELayerPlan",
    "TensorParallelDecodeLayerPlan",
    "TensorParallelPackedMoEFinalizer",
    "TensorParallelReplicatedLinear",
    "TensorParallelRoutePackedPlan",
    "TensorParallelVocab",
    "shard_linear_input",
    "shard_linear_output",
    "FixedMoEPrelude",
    "FixedMoEPreludeSpec",
    "vq_gemv",
    "vq_gemv_packed_list",
    "vq_relayout_block_major",
    "vq_relayout_row_tile",
    "vq_compile_u16_row_tile",
]
