"""Generate the compact builtin NVQ codebook header used by the C++ runtime."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from mfq.formats.nvq import D4_256, E8_256, NVQ2_E8, NVQ3_D4, pack_codebook
from mfq.formats.nvq1_l import IQ1S_TERNARY_2048, pack_ternary_codebook


def _words(payload: bytes) -> np.ndarray:
    return np.frombuffer(payload, dtype="<u2")


def _array(name: str, values: np.ndarray) -> str:
    lines = []
    for start in range(0, values.size, 12):
        row = ", ".join(f"0x{int(value):04x}" for value in values[start : start + 12])
        lines.append(f"    {row},")
    return (
        f"inline constexpr uint16_t {name}[{values.size}] = {{\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def generate() -> str:
    arrays = (
        _array("kNvq1LCodebookPacked", _words(pack_ternary_codebook(IQ1S_TERNARY_2048))),
        _array("kNvq2CodebookPacked", _words(pack_codebook(NVQ2_E8, E8_256))),
        _array("kNvq3CodebookPacked", _words(pack_codebook(NVQ3_D4, D4_256))),
    )
    return (
        "// Generated by mfq.tools.generate_nvq_cpp_codebooks.\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "namespace mfq::nvq_codebooks {\n\n"
        + "\n".join(arrays)
        + "\n}  // namespace mfq::nvq_codebooks\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate(), encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
